FROM eclipse-temurin:17-jdk AS compil
WORKDIR /app
COPY . .
CMD ["./mvnw", "clean", "package"]

FROM eclipse-temurin:17-jdk AS prod
WORKDIR /app

COPY --from=compile /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]